apiVersion: apps/v1
kind: Deployment
metadata:
  name: tjts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tjts-app
  template:
    metadata:
      labels:
        app: tjts-app
    spec:
      containers:
      - name: tjts-app
        image: testimage:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
